### ISSUE TITLE
Does the codebase support multi-view training as done in Table A6 of Appendix?

### ISSUE THREAD

**Issue by andrewsonga** [LemonATsu/A-NeRF#4]
Hello, 

First of all, thank you for releasing the code for your amazing research. I loved the fact that this paper tried from the get-go to make as few assumptions as possible and refrain from using too many human-specific priors.

My question is does the codebase support multi-view training _i.e._, training with multi-view video as done in Table A6 of the Appendix? I've found a flag in `run_nerf.py` that seems to refer to the use of multi-view video but it appears as though this flag isn't actually used during training of the NeRF: (https://github.com/LemonATsu/A-NeRF/blob/1b07b7aa2a0bd8d2f6bf13632b86760b4aa44e04/run_nerf.py#L447)

If the codebase doesn't yet support multi-view training, could you provide some advice as to how to modify the codebase to enable multi-view? For instance, how did you incorporate multi-view into the codebase when performing the experiments for Table A6?

Thank you in advance :)

**Comment by LemonATsu** [comment]
@andrewsonga the short answer is that: this repo sort of supported multiview training. Due to the data license issue, we are only able to provide codes as references to how we handle the multiview case, but the codes were not very complete.

I have updated the codes, and hopefully, it can be a better reference for you to try the uncalibrated multiview optimization.

Below are some pointers that I hope can help you trace what we did more easily:
- How does the optimization work?
We assume that we have (1) the knowledge of "what views have the same pose", and (2) "uncalibrated" cameras
Given this information, we (1) share the joint rotation parameters for the pose from the same view, but (2) maintain separated root rotation parameters for all images because we don't know the calibration between views.

- Where are they in the code?
So the first step we do is to group the images that share the same pose together, and "average" all the joint rotations except the root one as our initial pose: https://github.com/LemonATsu/A-NeRF/blob/main/core/load_h36m.py#L306

The function returns the initialized pose, as well as
1. `kp_map`: an index map that maps from image indices to unique pose indices. 
2. `kp_uidxs`: a list of indices of unique poses. 
Note that `len(kp_map) >= len(kp_uidxs)`, because in multiview cases we have `>=1 ` views per pose.

- How about the optimization code?
Here is what we did with `kp_uidxs` https://github.com/LemonATsu/A-NeRF/blob/main/core/pose_opt.py#L294
We create `N=len(kp_uidxs)` bone parameters for non-root joints, and keep `N=len(kp_map)` root rotation here.

And here is how we use `kp_map`: https://github.com/LemonATsu/A-NeRF/blob/main/core/pose_opt.py#L330
Whenever a pose is queried, we first retrieve the root rotation. We then look up `kp_map` to find which unique pose is the queried pose, and grab the pose from the mapped index.

The rest of the process is identical to the single view case.

As a final note, if your camera is calibrated, you can also just maintain `N=len(kp_uidxs)` root rotation, which I believe will give you even better refinement outcomes.

I hope the above information help.

**Comment by andrewsonga** [comment]
@LemonATsu Thank you for the detailed explanation!

I just have a follow-up question about the process of "group the images that share the same pose together". If the camera-agnostic human pose is characterized by N joint rotations, each of which are described by ${\mathcal{SO}(3)}$ matrices that have **_continuous_** entries, isn’t it highly likely that the human poses in different frames / views will be “unique”?
 
How many "unique pose" clusters are there?

**Comment by LemonATsu** [comment]
@andrewsonga Yes, you are right. All the poses are 'unique' in the sense that they are estimated separately, so the poses will always be different from each other (because of small estimation errors, etc).

Therefore, to group the pose together, we need to have prior knowledge on what poses should be the same. Take Human3.6m as an example, we get this prior knowledge by simply grouping the pose at the same time step from different cameras together. Simply put, we need the knowledge that "these poses are captured at the same time, but from different views/cameras" to do this optimization.

In principle, having that knowledge should also allow you to do camera calibration, which should give you better multi-view pose refinement. But we opt to not do that for simplicity.
